# -*- coding: utf-8 -*-
"""codegen_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8a2QME2RCEn6l2rO-qB6ToiIOgwizjM
"""

from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "Salesforce/codegen-350M-mono"
model = AutoModelForCausalLM.from_pretrained(checkpoint)
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

text = "def reverse_linked_list():"

completion = model.generate(**tokenizer(text, return_tensors="pt"), max_new_tokens=500)

print(tokenizer.decode(completion[0]))

